// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-trips.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/result.ts
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Connect your Junto account first." }],
    isError: true
  };
}
function failure(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function ok(data, structured) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    ...structured ? { structuredContent: structured } : {}
  };
}
function isAuthed(ctx) {
  return ctx.isAuthenticated() && Boolean(ctx.getUserId());
}

// src/lib/mcp/tools/list-trips.ts
var list_trips_default = defineTool({
  name: "list_trips",
  title: "List trips",
  description: "List the trips the signed-in Junto user is a member of, with dates and destination.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!isAuthed(ctx)) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("trips").select("id, name, trip_name, destination, tentative_start_date, tentative_end_date, status, emoji").order("tentative_start_date", { ascending: false });
    if (error) return failure(error.message);
    return ok(data ?? [], { trips: data ?? [] });
  }
});

// src/lib/mcp/tools/get-trip.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var get_trip_default = defineTool2({
  name: "get_trip",
  title: "Get trip details",
  description: "Get one trip with its members, itinerary items and ideas. Use the trip id from list_trips.",
  inputSchema: { trip_id: z.string().describe("Trip UUID.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ trip_id }, ctx) => {
    if (!isAuthed(ctx)) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: trip, error } = await supabase.from("trips").select("id, name, trip_name, destination, tentative_start_date, tentative_end_date, status, settlement_currency, emoji").eq("id", trip_id).maybeSingle();
    if (error) return failure(error.message);
    if (!trip) return failure("Trip not found, or you do not have access to it.");
    const [{ data: members }, { data: itinerary }, { data: ideas }] = await Promise.all([
      supabase.from("trip_members").select("user_id, role, attendance_status").eq("trip_id", trip_id),
      supabase.from("itinerary_items").select("id, day_date, start_time, end_time, title, location_text, status").eq("trip_id", trip_id).order("day_date", { ascending: true }).order("sort_order", { ascending: true }),
      supabase.from("trip_ideas").select("id, title, category, status").eq("trip_id", trip_id)
    ]);
    const result = { trip, members: members ?? [], itinerary: itinerary ?? [], ideas: ideas ?? [] };
    return ok(result, result);
  }
});

// src/lib/mcp/tools/list-expenses.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_expenses_default = defineTool3({
  name: "list_expenses",
  title: "List trip expenses",
  description: "List expenses recorded on a trip, most recent first.",
  inputSchema: { trip_id: z2.string().describe("Trip UUID.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ trip_id }, ctx) => {
    if (!isAuthed(ctx)) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("expenses").select("id, title, amount, currency, category, incurred_on, payer_id, split_type, notes").eq("trip_id", trip_id).order("incurred_on", { ascending: false }).limit(200);
    if (error) return failure(error.message);
    const total = (data ?? []).reduce((sum, e) => sum + Number(e.amount ?? 0), 0);
    return ok({ expenses: data ?? [], count: data?.length ?? 0, raw_total: total }, { expenses: data ?? [] });
  }
});

// src/lib/mcp/tools/add-expense.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var add_expense_default = defineTool4({
  name: "add_expense",
  title: "Add an expense",
  description: "Record a new expense on a trip, paid by the signed-in user.",
  inputSchema: {
    trip_id: z3.string().describe("Trip UUID."),
    title: z3.string().describe("What the expense was for."),
    amount: z3.number().describe("Amount in the given currency."),
    currency: z3.string().describe("ISO 4217 currency code, e.g. EUR."),
    incurred_on: z3.string().optional().describe("ISO date (YYYY-MM-DD). Defaults to today."),
    category: z3.string().optional().describe("Optional category, e.g. food, transport, stay."),
    notes: z3.string().optional().describe("Optional notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ trip_id, title, amount, currency, incurred_on, category, notes }, ctx) => {
    if (!isAuthed(ctx)) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("expenses").insert({
      trip_id,
      payer_id: ctx.getUserId(),
      title: title.trim(),
      amount,
      currency: currency.trim().toUpperCase(),
      incurred_on: incurred_on ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      category: category ?? null,
      notes: notes ?? null
    }).select("id, title, amount, currency, incurred_on, category").single();
    if (error) return failure(error.message);
    return ok(data, { expense: data });
  }
});

// src/lib/mcp/tools/add-itinerary-item.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var add_itinerary_item_default = defineTool5({
  name: "add_itinerary_item",
  title: "Add an itinerary item",
  description: "Add an activity to a trip's day-by-day itinerary.",
  inputSchema: {
    trip_id: z4.string().describe("Trip UUID."),
    day_date: z4.string().describe("ISO date (YYYY-MM-DD) for the day this happens."),
    title: z4.string().describe("Short activity title."),
    start_time: z4.string().optional().describe("Optional 24h start time, HH:MM."),
    end_time: z4.string().optional().describe("Optional 24h end time, HH:MM."),
    location_text: z4.string().optional().describe("Optional venue or address."),
    notes: z4.string().optional().describe("Optional notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!isAuthed(ctx)) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("itinerary_items").insert({
      trip_id: input.trip_id,
      day_date: input.day_date,
      title: input.title.trim(),
      start_time: input.start_time ?? null,
      end_time: input.end_time ?? null,
      location_text: input.location_text ?? null,
      notes: input.notes ?? null,
      created_by: ctx.getUserId()
    }).select("id, day_date, start_time, title, location_text").single();
    if (error) return failure(error.message);
    return ok(data, { item: data });
  }
});

// src/lib/mcp/tools/add-idea.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var add_idea_default = defineTool6({
  name: "add_idea",
  title: "Add a trip idea",
  description: "Add a suggestion to a trip's idea board for the group to consider.",
  inputSchema: {
    trip_id: z5.string().describe("Trip UUID."),
    title: z5.string().describe("The idea, e.g. 'Sunset kayak in Cala Llombards'."),
    category: z5.string().optional().describe("Optional category, e.g. food, activity, stay.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ trip_id, title, category }, ctx) => {
    if (!isAuthed(ctx)) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("trip_ideas").insert({ trip_id, title: title.trim(), category: category ?? null, created_by: ctx.getUserId() }).select("id, title, category, status").single();
    if (error) return failure(error.message);
    return ok(data, { idea: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "dwtbqomfleihcvkfoopm";
var mcp_default = defineMcp({
  name: "junto",
  title: "Junto",
  version: "0.1.0",
  instructions: "Tools for Junto, a group trip planner. Read the signed-in user's trips, itineraries, ideas and shared expenses, and add new expenses, itinerary items and ideas. Always call list_trips first to resolve a trip id before using the other tools.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_trips_default, get_trip_default, list_expenses_default, add_expense_default, add_itinerary_item_default, add_idea_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
